namespace Black.OpenGL;

public enum Capabilities : uint
{
    Blend                   = 0x0BE2,
    ClipDistance0           = 0x3000,
    ClipDistance1           = 0x3001,
    ClipDistance2           = 0x3002,
    ClipDistance3           = 0x3003,
    ClipDistance4           = 0x3004,
    ClipDistance5           = 0x3005,
    ClipDistance6           = 0x3006,
    ClipDistance7           = 0x3007,
    ColorLogicOP            = 0x0BF2,
    CullFace                = 0x0B44,
    DepthClamp              = 0x864F,
    DepthTest               = 0x0B71,
    Dither                  = 0x0BD0,
    FramebufferSrgb         = 0x8DB9,
    LineSmooth              = 0x0B20,
    Multisample             = 0x809D,
    PolygonOffsetFill       = 0x8037,
    PolygonOffsetLine       = 0x2A02,
    PolygonOffsetPoint      = 0x2A01,
    PolygonSmooth           = 0x0B41,
    PrimitiveRestart        = 0x8F9D,
    SampleAlphaToCoverage   = 0x809E,
    SampleAlphaToOne        = 0x809F,
    SampleCoverage          = 0x80A0,
    ScissorTest             = 0x0C11,
    StencilTest             = 0x0B90,
    TextureCubeMapSeamless  = 0x884F,
    ProgramPointSize        = 0x8642,
}

public enum BlendFactors : uint
{
    Zero                    = 0x0, 
    One                     = 0x1, 
    SrcColor                = 0x0300, 
    OneMinusSrcColor        = 0x0301, 
    SrcAlpha                = 0x0302, 
    OneMinusSrcAlpha        = 0x0303, 
    DstAlpha                = 0x0304, 
    OneMinusDstAlpha        = 0x0305, 
    DstColor                = 0x0306, 
    OneMinusDstColor        = 0x0307, 
    SrcAlphaSaturate        = 0x0308, 
    ConstantColor           = 0x8001, 
    OneMinusConstantColor   = 0x8002, 
    ConstantAlpha           = 0x8003, 
    OneMinusConstantAlpha   = 0x8004, 
    Src1Alpha               = 0x8589, 
    Src1Color               = 0x88F9, 
    OneMinusSrc1Color       = 0x88FA, 
    OneMinusSrc1Alpha       = 0x88FB,
}

public enum BlendEquations : uint
{
    FuncAdd                 = 0x8006,
    Min                     = 0x8007,
    Max                     = 0x8008,
    FuncSubtract            = 0x800A,
    FuncReverseSubtract     = 0x800B,
}

public enum TriangleFaces : uint
{
    Front                   = 0x0404,
    Back                    = 0x0405,
    FrontAndBack            = 0x0408,
}

public enum CompareFunctions : uint
{
    Never                   = 0x0200,
    Less                    = 0x0201,
    Equal                   = 0x0202,
    LessOrEqual             = 0x0203,
    Greater                 = 0x0204,
    NotEqual                = 0x0205,
    GreaterOrEqual          = 0x0206,
    Always                  = 0x0207,
}

public enum FrontFaceModes : uint
{
    Clockwise               = 0x0900,
    CounterClockwise        = 0x0901,
}

public enum ErrorFlags : uint
{
    NoError                             = 0x0,
    InvalidEnum                         = 0x0500,
    InvalidValue                        = 0x0501,
    InvalidOperation                    = 0x0502,
    InvalidFramebufferOperation         = 0x0506,
    OutOfMemory                         = 0x0505,
}

public enum HintTargets : uint
{
    LineSmoothHint                      = 0x0C52, 
    PolygonSmoothHint                   = 0x0C53, 
    TextureCompressionHint              = 0x84EF, 
    FragmentShaderDerivativeHint        = 0x8B8B,
}

public enum HintModes : uint
{
    Fastest         = 0x1101,
    Nicest          = 0x1102,
    DontCare        = 0x1100,
}

public enum LogicOperations : uint
{
    Clear                                   = 0x1500,
    Set                                     = 0x150F,
    Copy                                    = 0x1503,
    CopyInverted                            = 0x150C, 
    Noop                                    = 0x1505, 
    Invert                                  = 0x150A, 
    And                                     = 0x1501, 
    Nand                                    = 0x150E, 
    Or                                      = 0x1507, 
    Nor                                     = 0x1508, 
    Xor                                     = 0x1506, 
    Equiv                                   = 0x1509, 
    AndReverse                              = 0x1502, 
    AndInverted                             = 0x1504, 
    OrReverse                               = 0x150B,
    OrInverted                              = 0x150D,
}

public enum PixelStoreParameters : uint
{
    PackAlignment                           = 0x0D05, 
    PackImageHeight                         = 0x806C, 
    PackLsbFirst                            = 0x0D01, 
    PackRowLength                           = 0x0D02, 
    PackSkipImages                          = 0x806B,
    PackSkipPixels                          = 0x0D04, 
    PackSkipRows                            = 0x0D03, 
    PackSwapBytes                           = 0x0D00, 
    UnpackAlignment                         = 0x0CF5,
    UnpackImageHeight                       = 0x806E, 
    UnpackLsbFirst                          = 0x0CF1, 
    UnpackRowLength                         = 0x0CF2, 
    UnpackSkipImages                        = 0x806D, 
    UnpackSkipPixels                        = 0x0CF4, 
    UnpackSkipRows                          = 0x0CF3, 
    UnpackSwapBytes                         = 0x0CF0, 
}

public enum PointParameterNames : uint
{
    PointFadeThresholdSize                  = 0x8128,
    PointSpriteCoordOrigin                  = 0x8CA0,
}

public enum SpriteCoordOrigin : uint
{
    LowerLeft                               = 0x8CA1,
    UpperLeft                               = 0x8CA2,
}

public enum PolygonModes : uint
{
    Point                                   = 0x1B00,
    Line                                    = 0x1B01,
    Fill                                    = 0x1B02,
}

public enum StencilOperations : uint
{
    Keep                                    = 0x1E00, 
    Zero                                    = 0x0, 
    Replace                                 = 0x1E01, 
    Increment                               = 0x1E02, 
    IncrementWrap                           = 0x8507, 
    Decrement                               = 0x1E03, 
    DecrementWrap                           = 0x8508, 
    Invert                                  = 0x150A,
}

public enum GetParameterNames : uint
{
    ActiveTexture                           = 0x84E0,
    AliasedLineWidthRange                   = 0x846E,
    SmoothLineWidthGranularity              = 0x0B23,
    SmoothLineWidthRange                    = 0x0B22,
    ArrayBufferBinding                      = 0x846D,
    Blend                                   = 0x0BE2,
    BlendColor                              = 0x8005,
    BlendDstAlpha                           = 0x80CA,
    BlendDstRgb                             = 0x80C8,
    BlendEquationRgb                        = 0x8009,
    BlendEquationAlpha                      = 0x883D,
    BlendSrcAlpha                           = 0x80CB,
    BlendSrcRgb                             = 0x80C9,
    ColorClearValue                         = 0x0C22,
    ColorLogicOp                            = 0x0BF2,
    ColorWritemask                          = 0x0C23,
    CompressedTextureFormats                = 0x86A3,
    CullFace                                = 0x0B44,
    CurrentProgram                          = 0x8B8D,
    DepthClearValue                         = 0x0B73,
    DepthFunc                               = 0x0B74,
    DepthRange                              = 0x0B70,
    DepthTest                               = 0x0B71,
    DepthWritemask                          = 0x0B72,
    Dither                                  = 0x0BD0,
    Doublebuffer                            = 0x0C32,
    DrawBuffer                              = 0x0C01,
    DrawBuffer0                             = 0x8825,
    DrawBuffer1                             = 0x8826,
    DrawBuffer2                             = 0x8827,
    DrawBuffer3                             = 0x8828,
    DrawBuffer4                             = 0x8829,
    DrawBuffer5                             = 0x882A,
    DrawBuffer6                             = 0x882B,
    DrawBuffer7                             = 0x882C,
    DrawBuffer8                             = 0x882D,
    DrawBuffer9                             = 0x882E,
    DrawBuffer10                            = 0x882F,
    DrawBuffer11                            = 0x8830,
    DrawBuffer12                            = 0x8831,
    DrawBuffer13                            = 0x8832,
    DrawBuffer14                            = 0x8833,
    DrawBuffer15                            = 0x8834,
    DrawFramebufferBinding                  = 0x8CA6,
    ReadFramebufferBinding                  = 0x8CA7,
    ElementArrayBufferBinding               = 0x8895,
    RenderbufferBinding                     = 0x8CA7,
    FragmentShaderDerivativeHint            = 0x8B8B,
    LineSmooth                              = 0x0B20,
    LineSmoothHint                          = 0x0C52,
    LineWidth                               = 0x0B21,
    LogicOpMode                             = 0x0BF0,
    Max3DTextureSize                        = 0x8073,
    MaxClipDistances                        = 0x0D32,
    MaxCombinedFragmentUniformComponents    = 0x8A33,
    MaxCombinedTextureImageUnits            = 0x8B4D,
    MaxCombinedVertexUniformComponents      = 0x8A31,
    MaxCombinedGeometryUniformComponents    = 0x8A32,
    MaxVaryingComponents                    = 0x8B4B,
    MaxCombinedUniformBlocks                = 0x8A2E,
    MaxCubeMapTextureSize                   = 0x851C,
    MaxDrawBuffers                          = 0x8824,
    MaxDualSourceDrawBuffers                = 0x88FC,
    MaxElementsIndices                      = 0x80E9,
    MaxElementsVertices                     = 0x80E8,
    MaxFragmentUniformComponents            = 0x8B49,
    MaxFragmentUniformBlocks                = 0x8A2D,
    MaxFragmentInputComponents              = 0x9125,
    MinProgramTexelOffset                   = 0x8904,
    MaxProgramTexelOffset                   = 0x8905,
    MaxRectangleTextureSize                 = 0x84F8,
    MaxTextureImageUnits                    = 0x8872,
    MaxTextureLodBias                       = 0x84FD,
    MaxTextureSize                          = 0x0D33,
    MaxRenderbufferSize                     = 0x84E8,
    MaxArrayTextureLayers                   = 0x88FF,
    MaxTextureBufferSize                    = 0x8C2B,
    MaxUniformBlockSize                     = 0x8A30,
    MaxVaryingFloats                        = 0x8B4B,
    MaxVertexAttribs                        = 0x8869,
    MaxVertexTextureImageUnits              = 0x8B4C,
    MaxGeometryTextureImageUnits            = 0x8C29,
    MaxVertexUniformComponents              = 0x8B4A,
    MaxVertexOutputComponents               = 0x9122,
    MaxGeometryUniformComponents            = 0x8DDF,
    MaxSampleMaskWords                      = 0x8E59,
    MaxColorTextureSamples                  = 0x910E,
    MaxDepthTextureSamples                  = 0x910F,
    MaxIntegerSamples                       = 0x9110,
    MaxServerWaitTimeout                    = 0x9111,
    MaxUniformBufferBindings                = 0x8A2F,
    UniformBufferOffsetAlignment            = 0x8A34,
    MaxVertexUniformBlocks                  = 0x8A2B,
    MaxGeometryUniformBlocks                = 0x8A2C,
    MaxGeometryInputComponents              = 0x9123,
    MaxGeometryOutputComponents             = 0x9124,
    MaxViewportDims                         = 0x0D3A,
    NumCompressedTextureFormats             = 0x86A2,
    PackAlignment                           = 0x0D05,
    PackImageHeight                         = 0x806C,
    PackLsbFirst                            = 0x0D01,
    PackRowLength                           = 0x0D02,
    PackSkipImages                          = 0x806B,
    PackSkipPixels                          = 0x0D04,
    PackSkipRows                            = 0x0D03,
    PackSwapBytes                           = 0x0D00,
    PixelPackBufferBinding                  = 0x88ED,
    PixelUnpackBufferBinding                = 0x88EF,
    PointFadeThresholdSize                  = 0x8128,
    PrimitiveRestartIndex                   = 0x8F9E,
    ProgramPointSize                        = 0x8642,
    ProvokingVertex                         = 0x8E4F,
    PointSize                               = 0x0B11,
    PointSizeGranularity                    = 0x0B13,
    PointSizeRange                          = 0x0B12,
    PolygonMode                             = 0x0B40,
    PolygonOffsetFactor                     = 0x8038,
    PolygonOffsetFill                       = 0x8037,
    PolygonOffsetLine                       = 0x2A02,
    PolygonOffsetPoint                      = 0x2A01,
    PolygonOffsetUnits                      = 0x2A00,
    PolygonSmooth                           = 0x0B41,
    PolygonSmoothHint                       = 0x0C53,
    ReadBuffer                              = 0x0C02,
    SampleBuffers                           = 0x80A8,
    SampleCoverageInvert                    = 0x80AB,
    SampleCoverageValue                     = 0x80AA,
    SamplerBinding                          = 0x8919,
    Samples                                 = 0x80A9,
    ScissorBox                              = 0x0C10,
    ScissorTest                             = 0x0C11,
    StencilBackFail                         = 0x8CA5,
    StencilBackFunc                         = 0x8CA4,
    StencilBackPassDepthFail                = 0x8CA3,
    StencilBackPassDepthPass                = 0x8803,
    StencilBackRef                          = 0x8802,
    StencilBackValueMask                    = 0x8800,
    StencilBackWritemask                    = 0x8801,
    StencilClearValue                       = 0x0B91,
    StencilFail                             = 0x0B94,
    StencilFunc                             = 0x0B92,
    StencilPassDepthFail                    = 0x0B95,
    StencilPassDepthPass                    = 0x0B96,
    StencilRef                              = 0x0B97,
    StencilTest                             = 0x0B90,
    StencilValueMask                        = 0x0B93,
    StencilWritemask                        = 0x0B98,
    Stereo                                  = 0x0C33,
    SubpixelBits                            = 0x0D50,
    TextureBinding1D                        = 0x8068,
    TextureBinding1DArray                   = 0x8C1C,
    TextureBinding2D                        = 0x8069,
    TextureBinding2DArray                   = 0x8C1D,
    TextureBinding2DMultisample             = 0x9104,
    TextureBinding2DMultisampleArray        = 0x9105,
    TextureBinding3D                        = 0x806A,
    TextureBindingBuffer                    = 0x8C2C,
    TextureBindingCubeMap                   = 0x8514,
    TextureBindingRectangle                 = 0x84F6,
    TextureCompressionHint                  = 0x84EF,
    Timestamp                               = 0x8E28,
    TransformFeedbackBufferBinding          = 0x8C8F,
    TransformFeedbackBufferSize             = 0x8C85,
    TransformFeedbackBufferStart            = 0x8C84,
    UniformBufferBinding                    = 0x8A28,
    UniformBufferSize                       = 0x8A2A,
    UniformBufferStart                      = 0x8A29,
    UnpackAlignment                         = 0x0CF5,
    UnpackImageHeight                       = 0x806E,
    UnpackLsbFirst                          = 0x0CF1,
    UnpackRowLength                         = 0x0CF2,
    UnpackSkipImages                        = 0x806D,
    UnpackSkipPixels                        = 0x0CF4,
    UnpackSkipRows                          = 0x0CF3,
    UnpackSwapBytes                         = 0x0CF0,
    NumExtensions                           = 0x821D,
    MajorVersion                            = 0x821B,
    MinorVersion                            = 0x821C,
    ContextFlags                            = 0x821E,
    VertexArrayBinding                      = 0x85B5, 
    Viewport                                = 0x0BA2,
}